### ISSUE TITLE
Elasticsearch 5.0 support

### ISSUE THREAD

**Issue by superawesome** [untergeek/es_stats_zabbix#2]
$ es_stats_zabbix --configuration /etc/zabbix/es_stats_zabbix.ini single health[status]
Expected Elasticsearch version range > 1.0.0 < 3.0.0
ERROR: Incompatible with version 5.0.0 of Elasticsearch.  Exiting.

Any chance of this getting updated to support ES 5? Not sure how much needs changed, AFAICT most of the status-related HTTP calls seem the same. Hopefully nothing more than a rebuild.

Note: I haven't checked if this is actually an issue with es_stats_zabbix or the underlying es_stats... if the latter, lmk and I can close this and open an issue on that project instead. :)

**Comment by untergeek** [comment]
This has been covered in recent merges.  Wait for the next big release, which will support Elasticsearch versions 2.x - 6.x.
